/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { EnumToolCategory } from "./EnumToolCategory";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { PromotionUpdateManyWithoutToolsInput } from "./PromotionUpdateManyWithoutToolsInput";
import { Type } from "class-transformer";
import { RatingUpdateManyWithoutToolsInput } from "./RatingUpdateManyWithoutToolsInput";
import { TransactionUpdateManyWithoutToolsInput } from "./TransactionUpdateManyWithoutToolsInput";

@InputType()
class ToolUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  authorizationDetails?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumToolCategory,
  })
  @IsEnum(EnumToolCategory)
  @IsOptional()
  @Field(() => EnumToolCategory, {
    nullable: true,
  })
  category?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  features?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  monthlyPaymentDetails?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  pictures?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => PromotionUpdateManyWithoutToolsInput,
  })
  @ValidateNested()
  @Type(() => PromotionUpdateManyWithoutToolsInput)
  @IsOptional()
  @Field(() => PromotionUpdateManyWithoutToolsInput, {
    nullable: true,
  })
  promotions?: PromotionUpdateManyWithoutToolsInput;

  @ApiProperty({
    required: false,
    type: () => RatingUpdateManyWithoutToolsInput,
  })
  @ValidateNested()
  @Type(() => RatingUpdateManyWithoutToolsInput)
  @IsOptional()
  @Field(() => RatingUpdateManyWithoutToolsInput, {
    nullable: true,
  })
  ratings?: RatingUpdateManyWithoutToolsInput;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutToolsInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutToolsInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutToolsInput, {
    nullable: true,
  })
  transactions?: TransactionUpdateManyWithoutToolsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  yearlyPaymentDetails?: number | null;
}

export { ToolUpdateInput as ToolUpdateInput };
